server:
  port: 8088 # æœåŠ¡ç«¯å£

spring:
  # æ•°æ®åº“è¿æ¥
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lost_found_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update  # å¼€å¯è‡ªåŠ¨æ›´æ–°è¡¨ç»“æ„ï¼ˆErupt éœ€è¦è¿™ä¸ªæ¥åˆ›å»ºç³»ç»Ÿè¡¨ï¼‰
    show-sql: true      # (å¯é€‰) åœ¨æ§åˆ¶å°æ‰“å° SQLï¼Œæ–¹ä¾¿è°ƒè¯•
  # æ–‡ä»¶ä¸Šä¼ 
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis-Plus é…ç½® (è¿™é‡Œæ˜¯ä½ ä¿®æ”¹æ­£ç¡®çš„å…³é”®ç‚¹)
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.li.lostbackend.entity # âœ… è¿™é‡Œå¿…é¡»æ˜¯ com.li...
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# æ—¥å¿—é…ç½®
logging:
  level:
    com.li: debug
    root: info

# ğŸ‘‡ğŸ‘‡ğŸ‘‡ å¿…é¡»å¦èµ·ä¸€è¡Œï¼Œé¡¶æ ¼å†™ï¼Œä¸è¦æœ‰ç¼©è¿› ğŸ‘‡ğŸ‘‡ğŸ‘‡
erupt:
  csrf-inspect: false
  uploadPath: /opt/erupt-attachment